[project]
name = "mqtt-app"
version = "0.1.0"
description = "A simple MQTT publisher/subscriber example"

readme = ""
requires-python = ">=3.8"
dependencies = ["paho-mqtt",
"slack-sdk",
"python-dotenv"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"